### ISSUE TITLE
Sandbox confuses WebSocket connection ids

### ISSUE THREAD

**Issue by andybee** [architect/architect#818]
**Describe the issue**

When running Sandbox with a WebSocket setup and creating 2x connections, the second connection gets assigned the same connection ID as the first.

**Steps to reproduce**
1. Check out this [example repo](https://github.com/andybee/architect-ws-issue-demo).
2. Start Sandbox and connect to http://localhost:3333/
3. Click 'Connect' on connection 1, then 'Connect' on connection 2. Observe the ID each connection receives.
4. Click 'Disconnect' on connection 1. Observe the id this connection returns.

**Expected behavior**

I would expect the disconnect callback to contain the same ID as the initial connection for Connection 1. Instead I get the second connection's ID.

*Connection 1 connects:*
```
Invoking ws/connect WebSocket Lambda
connect 9102a66e-2dfd-4c91-b511-c85f36db31bd
```
*Connection 2 connects:*
```
Invoking ws/connect WebSocket Lambda
connect 7951cd60-dd54-47bc-bd4f-b08a42332dbb
```
*Connection 1 disconnects:*
```
Invoking ws/disconnect WebSocket Lambda
disconnect 7951cd60-dd54-47bc-bd4f-b08a42332dbb
```
Wrong ID, this is the ID given to connection 2.

*Connection 2 disconnects*
```
Invoking ws/disconnect WebSocket Lambda
disconnect 7951cd60-dd54-47bc-bd4f-b08a42332dbb
```
Same ID as the first disconnection.

**Comment by andybee** [comment]
As an aside, this codebase also throws an error when trying to send via `ws.send`:

```Failed to ws.send TypeError: Cannot read property 'send' of undefined```

**Comment by andybee** [comment]
Tracked down the issue to inside Sandbox [`src/http/register-websocket.js`](https://github.com/architect/sandbox/blob/db02bf2f904a7a6a613e289c1466708c6d15dc76/src/http/register-websocket.js#L14) - the connection ID is assigned to a variable up top when an upgrade attempt comes in, so when the second connection comes in this value is changed and we lose the reference to the original.

**Comment by brianleroux** [comment]
ok, so I'll have to build a demo to repro and want to be sure I'm following: you have a web page that tries to make two upgrade requests. even though there's one client you want the browser to open two sockets from one client ?

**Comment by andybee** [comment]
That isn’t what I actually want to do, it’s just what I quickly implemented in my demo repo to simulate it more easily:

https://github.com/andybee/architect-ws-issue-demo

It occurs any way 2 or more clients are simultaneously connected via a WebSocket to Sandbox, making it impossible to test “stateful” logic between 2 clients locally.

**Comment by brianleroux** [comment]
ah perfect, ok thx! I'll bbiab!

**Comment by brianleroux** [comment]
ok this was super helpful and def uncovered some timing issues with how we've authored web socket support. I can fix that but its going to take a minute. (I do not know how long that minute is tho!) And that answer is unsatisfying and unhelpful to us both! The root cause is we're keeping track of connection clients in the 'connect' event but you're firing a `arc.ws.send` before that logic has triggered (by doing the send in the connect event). 

I think we can workaround this however. My guess is you're trying to model multiple rooms or channels for one client. For example, Slack has many channels and you want to send data appropriately through those channels. The thing to notice however is that slack does not open a brand new web socket connection for every channel. It opens one socket and uses some identifier on the messages to route correctly. Is my assumption about what you're trying to model correct? (If so I can help by creating a quick demo that models that using dynamo and/or begin/data.)

**Comment by andybee** [comment]
This is where the fact I've reported two bugs might get a bit confusing, I'll try and address both to reduce the confusion. In summary though, the actual app uses a single socket, but there are multiple users.

**Connection ID gets confused**

This is the main issue I'm facing. In Sandbox, when a second user joins (in another tab, another browser, or in my dumb demo for simplicity - connection #2) a new ID is issued to them, but internally the variable is updated so that when I message in from the first connection, the connection ID in the event is wrong - it's the one issued to the second connection. So if you try and persist data in any way, for example I'm using DynamoDB to hold a list of "everyone online", I can't remove that user on disconnect because the event connection ID is now the second connection's ID.

**ws.send error**

I only discovered this when trying to implement a quick thing in the demo to send the connection id back to the connected client to display in the browser. I stopped when this didn't work and wondered if it was related or not.

**Comment by brianleroux** [comment]
hey @andybee thx for sticking w me here! if you're feelin ambitious https://github.com/architect/sandbox/pull/360 should fix this behavior. gonna review and hopefully get this on mainline tonight/tomorrow.

**Comment by brianleroux** [comment]
ok, you can try the new sandbox by adding it directly: `npm i @architect/sandbox@1.10.1-RC.0` !

**Comment by andybee** [comment]
I had to delete Sandbox from inside the local @architect/architect package before it would use the directly installed one, but that is now resolving the issue with connection ids - thanks!

Still have a problem with sending during the connection handler:

`Failed to ws.send Error: GoneException: 410`

I'm unsure if AWS supports this, the idea is I need to deliver some information on the first connection. Is there a preferred way to do this if it can't be done?

**Comment by brianleroux** [comment]
yes that error is what AWS itself does! you cannot send a message to a connection within the connection event (I have a modified example based on your repro code I can share…whats the best way to get you a .zip ?)

**Comment by andybee** [comment]
Could you throw the connection event handler in a Gist? Or is it wider than that?
